#!/system/bin/sh
#
# A XY Script to:
# Clean the "Folletto Style"
#

rm -f /data/tombstones/*;
rm -f /data/anr/*;
rm -f /cache/*.apk;
rm -f /cache/*.tmp;
rm -f /data/system/dropbox/*;
rm -f /data/dalvik-cache/*.apk;
rm -f /data/dalvik-cache/*.tmp;
