#!/system/bin/sh
#
# A XY Script
# Zipaligning to reading faster APKS
# Zipaligning = Sorting Apks as 4 bytes
#

LOG_FILE=/data/xy/zipalign.log
ZIPALIGNDB=/data/xy/zipalign.db

if [ -e $LOG_FILE ]; then
    rm $LOG_FILE;
fi;

if [ ! -f $ZIPALIGNDB ]; then
    touch $ZIPALIGNDB;
fi;

echo "-------------------------------------------------------------" | tee -a $LOG_FILE
echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE

for DIR in /system/app /data/app ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
     echo "Already checked: $DIR/$APK" | tee -a $LOG_FILE
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        echo "Already aligned: $DIR/$APK" | tee -a $LOG_FILE
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      else
        echo "Now aligning: $DIR/$APK" | tee -a $LOG_FILE
        zipalign -f 4 $APK /cache/$APK
        mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        rm -f /cache/$APK
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done

mount -o ro,remount /system
touch $ZIPALIGNDB
echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE
echo "-------------------------------------------------------------" | tee -a $LOG_FILE
