#!/system/bin/sh
# PrimeDirective, Sonicxml, DHO, Nuclearmistake
# With inspiration from DroidTh3ory

sync
sysrw

# IO Tweaks
BLOCK_DEVS=`ls -d /sys/block/mmc*`;
BLOCK_DEVS="$BLOCK_DEVS `ls -d /sys/block/mtd*`";
BLOCK_DEVS="$BLOCK_DEVS `ls -d /sys/block/dm-*`";

for i in $BLOCK_DEVS;
do
    echo "0" > $i/queue/rotational; 
    echo "16" > $i/queue/iosched/fifo_batch;
    echo "256" > $i/queue/max_sectors_kb;
done;

# Enable Sysctl Tweaks
sysctl -p /system/etc/sysctl.conf

# Set SD Card Cache
echo "2432" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;

# Breaking the lease
echo "15" > /proc/sys/fs/lease-break-time

# TCP Tweaks
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout;
echo "404480" > /proc/sys/net/core/wmem_max;
echo "404480" > /proc/sys/net/core/rmem_max;
echo "256960" > /proc/sys/net/core/rmem_default;
echo "256960" > /proc/sys/net/core/wmem_default;
echo "4096 16384 404480" > /proc/sys/net/ipv4/tcp_wmem;
echo "4096 87380 404480" > /proc/sys/net/ipv4/tcp_rmem;
setprop net.tcp.buffersize.default 4096,87380,404480,4096,16384,404480;
setprop net.tcp.buffersize.wifi 4096,87380,404480,4096,16384,404480;
setprop net.tcp.buffersize.umts 4096,87380,404480,4096,16384,404480;

sync
sysro
