#!/system/bin/sh
# PrimeDirective, Sonicxml, DHO, Nuclearmistake
# With inspiration from DroidTh3ory

sync
sysrw

# IO Tweaks
BLOCK_DEVS=`ls -d /sys/block/mmc*`;
BLOCK_DEVS="$BLOCK_DEVS `ls -d /sys/block/mtd*`";
BLOCK_DEVS="$BLOCK_DEVS `ls -d /sys/block/dm-*`";

for i in $BLOCK_DEVS;
do
    echo "0" > $i/queue/rotational; 
    echo "16" > $i/queue/iosched/fifo_batch;
    echo "256" > $i/queue/max_sectors_kb;
done;

# Enable Sysctl Tweaks
sysctl -p /system/etc/sysctl.conf

# Set SD Card Cache
echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;

# Breaking the lease
echo "15" > /proc/sys/fs/lease-break-time

sync
sysro
