#!/system/bin/sh
# PrimeDirective, Sonicxml, DHO, Nuclearmistake
# With inspiration from DroidTh3ory

sync
sysrw


#
# Enable Sysctl Tweaks
#
sysctl -p /system/etc/sysctl.conf


busybox rm -f /cache/*.apk
busybox rm -f /cache/*.tmp
busybox rm -f /data/dalvik-cache/*.apk
busybox rm -f /data/dalvik-cache/*.tmp

#
# Set SD Card Cache
#
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi


#
#
# Sysctl & VM Tweaks
#
busybox sysctl -w vm.page-cluster=3
busybox sysctl -w vm.drop_caches=3
busybox sysctl -w vm.dirty_expire_centisecs=750
busybox sysctl -w vm.dirty_writeback_centisecs=1500
busybox sysctl -w kernel.random.write_wakeup_threshold=256
busybox sysctl -w kernel.random.read_wakeup_threshold=128
busybox sysctl -w kernel.panic=0
busybox sysctl -w kernel.panic_on_oops=1
busybox sysctl -w kernel.msgmni=2048
busybox sysctl -w kernel.msgmax=64000
busybox sysctl -w kernel.shmmax=268435500
busybox sysctl -w kernel.sem=500,512000,64,2048
busybox sysctl -w kernel.sched_child_runs_first=0
busybox sysctl -w kernel.threads-max=525810
echo "1" > /proc/sys/vm/laptop_mode


# Vibration
echo 1498 > /sys/vibe/pwmduty

#
# File System Tweaks & Cleanup
#
echo "10" > /proc/sys/fs/lease-break-time


# Optimize Vm
#
if [ -e /proc/sys/vm/vfs_cache_pressure ]; then
	echo "10" > /proc/sys/vm/vfs_cache_pressure
fi

if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
	echo "500" > /proc/sys/vm/dirty_expire_centisecs
fi

if [ -e /proc/sys/vm/dirty_writeback_centisecs ]; then
	echo "1000" > /proc/sys/vm/dirty_writeback_centisecs
fi

if [ -e /proc/sys/vm/dirty_ratio ]; then
	echo "90" > /proc/sys/vm/dirty_ratio
fi

if [ -e /proc/sys/vm/dirty_background_ratio ]; then
	echo "45" > /proc/sys/vm/dirty_background_ratio
fi

if [ -f "\$i" ]; then
	sync;
	echo "cfq" > \$i;
fi


sync
sysro

