PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/crespo.mk \
    $(LOCAL_DIR)/crespo4g.mk \
    $(LOCAL_DIR)/d2att.mk \
    $(LOCAL_DIR)/d2spr.mk \
    $(LOCAL_DIR)/d2tmo.mk \
    $(LOCAL_DIR)/d2vzw.mk \
    $(LOCAL_DIR)/grouper.mk \
    $(LOCAL_DIR)/m7.mk \
    $(LOCAL_DIR)/maguro.mk \
    $(LOCAL_DIR)/mako.mk \
    $(LOCAL_DIR)/tilapia.mk \
    $(LOCAL_DIR)/toro.mk \
    $(LOCAL_DIR)/toroplus.mk \
    $(LOCAL_DIR)/i9100g.mk \
    $(LOCAL_DIR)/i9100.mk \
    $(LOCAL_DIR)/i9300.mk \
    $(LOCAL_DIR)/i9305.mk \
    $(LOCAL_DIR)/jfltetmo.mk \
    $(LOCAL_DIR)/n7100.mk \
    $(LOCAL_DIR)/p3100.mk \
    $(LOCAL_DIR)/leo.mk \
    $(LOCAL_DIR)/tf101.mk \
    $(LOCAL_DIR)/t0lte.mk \
    $(LOCAL_DIR)/t0lteatt.mk \
    $(LOCAL_DIR)/t0ltetmo.mk \
    $(LOCAL_DIR)/i605.mk \
    $(LOCAL_DIR)/l900.mk \
    $(LOCAL_DIR)/p4wifi.mk
